config/routes.rb
Rails.application.routes.draw do
  root "questions#index"
  resources :questions, except: [:show] do
    resources :answers, except: [:new, :show, :edit, :destroy, :update]
  end

  resources :answers, only: [:update]
  resources :users, only: [:new, :update, :destroy]

  get "/auth/:provider/callback", to: "sessions#create"
  
  delete '/logout', to: 'sessions#destroy'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  # belongs_to :user

  validates :description, presence: true, length: { minimum: 50 }
  validates :best, inclusion: { in: [true, false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  # belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :questions
  # has_many :answers

  def self.find_or_create_from_auth(auth)
    provider = auth['provider']
    uid = auth['uid']

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.username = auth['info']['nickname']
      user.name = auth['info']['name']
    end

  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers.order(best: :desc, created_at: :desc)
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:success] = "Answer saved correctly."
      redirect_to question_answers_path(@question)
    else
      flash[:alert] = @answer.errors.full_messages.to_sentence
      redirect_to question_answers_path(@question)
    end
  end

  def update
    @answer = Answer.find(params[:id])

    @question = @answer.question
    @question.answers.each do |test_answer|
      test_answer.best = false
      test_answer.save
    end
    @answer.best = true

    if @answer.save
      flash[:success] = "Answer marked as best answer."
      redirect_to question_answers_path(@answer.question)
    else
      flash[:alert] = "There was an error."
      redirect_to question_answers_path(@answer.question)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    redirect_to questions_path unless current_user
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:success] = "Question saved successfully."
      redirect_to question_answers_path(@question)
    else
      flash[:alert] = @question.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      flash[:success] = "Question saved successfully."
      redirect_to question_answers_path(@question)
    else
      flash[:alert] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    # @question = Question.find(params[:id])
    Question.where(id: params[:id]).destroy_all
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to questions_path, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/answers/_answer.html.erb
<% if answer.best %>
  <div class="answer card best">
<% else %>
  <div class="answer card">
<% end %>

  <div class="card-section">
    <p>
      <%= markdown(answer.description) %>
    </p>
  </div>
  <div class="card-section">
    <%= button_to "Best Answer", answer_path(answer), method: :put %>
  </div>
</div>

app/views/answers/index.html.erb
<div class="card">
  <div class="card-divider">
    <h1 class='question_title' > <%= @question.title %></h1>
  </div>
  <div class="card-section">
    <%= markdown(@question.description) %>
  </div>
  <div class="card-section">
    <%= button_to "Edit Question", edit_question_path(@question), method: :get, class: 'success button' %>
    <%= button_to "Delete Question", @question, method: :delete, class: 'alert button' %>
  </div>
</div>



<%= render partial: "answer", collection: @answers %>

<%= form_for [@question, @answer] do |f| %>

  <%= f.text_area :description, placeholder: "Your Answer Here", size: "20x6" %>
  <%= f.submit "Post Answer", class: 'button' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css" integrity="sha256-itWEYdFWzZPBG78bJOOiQIn06QCgN/F0wMDcC4nOhxY=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text">
            <%= link_to 'Rescue Mission', questions_path, class: "menu-text" %>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li>
            <%= button_to "New Question", new_question_path, method: :get, class: 'button' %>
          </li>
          <li>
            <% if current_user %>
              <ul class="menu">
                <li><%= "#{current_user.name}" %></li>
                <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
              </ul>
            <% else %>
              <%= link_to "Sign in with Github", "/auth/github" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% if flash.any? %>
      <div class="flash">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "callout #{name}" %>
        <% end %>
      </div>
    <% end %>

    <div class='row'>
      <%= yield %>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/js/foundation.min.js" integrity="sha256-Nd2xznOkrE9HkrAMi4xWy/hXkQraXioBg9iYsBrcFrs=" crossorigin="anonymous"></script>

  </body>
</html>

app/views/questions/_question_form.html.erb
<%= form_for(@question) do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, size: "20x10" %>
</div>
<div class="actions">
  <%= f.submit class: 'button' %>
</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Your Question</h1>

<%= button_to "Delete Question", @question, method: :delete, class: 'alert button' %>
<%= render "question_form" %>

app/views/questions/index.html.erb
<div class='small-centered columns'>
  <h1>All Questions</h1>
</div>

<% @questions.each do |question| %>

<div class="column">
   <div class="card">
     <div class="card-section">
       <h3><%= link_to question.title, question_answers_path(question) %></h3>
     </div>
   </div>
 </div>

<% end %>

app/views/questions/new.html.erb
<h1>Submit a New Question</h1>

<%= render "question_form" %>

app/views/questions/show.html.erb
<div class="card">
  <div class="card-divider">
    <h1 class='question_title' > <%= @question.title %></h1>
  </div>
  <div class="card-section">
    <%= markdown(@question.description) %>
  </div>
  <div class="card-section">
    <%= button_to "Edit Question", edit_question_path(@question), method: :get, class: 'success button' %>
    <%= button_to "Delete Question", @question, method: :delete, class: 'alert button' %>
  </div>
</div>



<%= render partial: "answer", collection: @answers %>

<%= form_for [@question, @answer] do |f| %>

  <%= f.text_area :description, placeholder: "Your Answer Here", size: "20x6" %>
  <%= f.submit "Post Answer", class: 'button' %>

<% end %>